### ISSUE TITLE
Bug: Graphql call is potentially insecure

### ISSUE THREAD

**Issue by nvanheuverzwijn** [OpsLevel/backstage-plugin#490]
### Environment

Calls to graphql endpoint are insecure (see https://github.com/OpsLevel/backstage-plugin/blob/a2a47db08468dbda27e51fe7a5c8b44cd29b489e/src/api.ts#L81)

Documentation requires us to use backstage proxy configuration which, by default since version 1.28, is now requiring to send backstage user jwt token via Authorization HTTP header. This is in direct conflict with opslevel proxy settings that sets a static opslevel api token. The workaround is to add `credentials: dangerously-allow-unauthenticated` in the proxy setting. However, this allows anyone on the internet to use our backstage instance as an unauthenticated proxy to our opslevel account.

A potential solution would be to add an oauth endpoint in opslevel, ask the backstage user to authenticate using backstage scmAuth api and use the oauth token in the graphql API. This would secure the endpoint and allow using `credentials: dangerously-allow-unauthenticated` without risk.

### What did you do?

<details>
<summary>Configuration</summary>

```
opslevel:
  baseUrl: 'https://app.opslevel.com'

proxy:
  endpoints:
    '/opslevel':
      target: 'https://app.opslevel.com'
      headers:
        X-Custom-Source: backstage
        Authorization: Bearer ${OPSLEVEL_API_KEY}
      allowedHeaders: ['GraphQL-Visibility']
```
</details>

### What did you expect to happen?

Opslevel should ask user authentication instead of using a global token.

### What actually happened?

Anyone can use a backstage instance configured with opslevel to bypass backstage's authentication and directly use the proxy configured opslevel api key.
